### ISSUE TITLE
Incorrect parsing of compilation-mode buffers

### ISSUE THREAD

**Issue by wildwestrom** [rust-lang/rust-mode#452]
Related to https://github.com/syl20bnr/spacemacs/issues/15643

### Description :octocat:
The wrong parts of a `compilation-mode` buffer are parsed for certain messages.
This isn't just aesthetics. The part highlighted in red is supposed to be the file name. The part highlighted in blue is supposed to be the location in the file.
When I click on the file name, it thinks the red portion is a file, and therefore can't find it, because the actual file is `(dirname/filename\.ext):\d+` not `(dirname/filename\.ext:\d+)`.

### Reproduction guide :beetle:
- Start Emacs
- Open a scratch buffer
- Paste the following text:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Could not get string from shell command.
             at src/main.rs:81:14

Caused by:
   0: Broken pipe (os error 32)
             at src/main.rs:79:14
      - Failed to write buffer to stdin', src/main.rs:412:28
```
- `M-x compilation-mode`
- Try opening the first or second highlighted file.

#### *Observed behaviour:*
Here's an example of what I see:
Image here:
![image](https://user-images.githubusercontent.com/77174844/178134241-41892a2e-be89-43fa-8829-987df9fe5c4b.png)
Notice that highlighting starts at black at ` at ` then red at `src/main.rs:81` then black at `:` then blue at `14`. When I click on the first or second highlighted files, it tries to navigate to `filename:linenumber` then go to the column-number.
On a minimal configuration of GNU Emacs, I see this:
![image](https://user-images.githubusercontent.com/77174844/178134475-6b54c7dd-fbff-4d52-ab3c-83300f99ffd6.png)
This indicates that something in spacemacs enhances `compilation-mode`. ~~I have no idea what exactly does it or how to search for it.~~
A minimal config of spacemacs will yield the same result, until the rust layer is added.
I also found information dealing with `compilation-mode` in [rust-compile.el](https://github.com/rust-lang/rust-mode/blob/master/rust-compile.el) therefore I assume this bug is in this package.
![image](https://user-images.githubusercontent.com/77174844/178135560-5aa808fe-135b-45f4-a64b-d1c51557056b.png)

#### *Expected behaviour:*
Same thing as above, except the text should be highlighted as follows.
Start red highlight at `src/main.rs` then black at `:` then blue after the first colon and navigate to the correct file and go to the correct line number.

**Comment by wildwestrom** [comment]
I have a good reason to believe this bug is upstream, but I think it's worth waiting for a response from the people working on rust-mode via https://github.com/rust-lang/rust-mode/issues/452.

**Comment by wildwestrom** [comment]
Just to be clear, made this issue just to get feedback before starting to implement the fix.

**Comment by wildwestrom** [comment]
Here's what I got so far. It works great!
```emacs-lisp
  (setq error_stack-regexps
    '("\\(?:at\\|',\\) \\(\\([^:\s]+\\):\\([0-9]+\\)\\)"
      2 3 nil nil 1))
  (setf (cdr (assoc 'cargo compilation-error-regexp-alist-alist))
        error_stack-regexps)
```
![image](https://user-images.githubusercontent.com/77174844/179173540-c38f536c-798b-4464-9390-9b42118bbc9f.png)

**Comment by brotzeit** [comment]
Sorry for the late reply. You're right:

#s(compilation--message
   (nil 28
        (("- Failed to write buffer to stdin', src/main.rs:412" nil)
         nil
         (28 #1))
        nil nil)
   2 nil cucumber)

Open a pr and I'll merge your fix, thanks!
